// <auto-generated />
namespace CadastroUrlBackendMobile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CriadoTabelaUrlBackendMobileTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriadoTabelaUrlBackendMobileTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907021304472_Criado Tabela UrlBackendMobileTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
